apiVersion: v1
kind: ConfigMap
metadata:
  name: mssql
  labels:
    app: mssql
data:
  primary.cnf: |
    # Apply this config only on the primary.
    [mssqld]
    log-bin    
  replica.cnf: |
    # Apply this config only on replicas.
    [mssqld]
    super-read-only 